
/* INNER */
SELECT *
FROM CLIENTE
INNER JOIN VENTA
ON CLIENTE.idCliente = VENTA.CLIENTE_idCliente

/* LEFT */
SELECT *
FROM EMPLEADO
LEFT JOIN VENTA
ON EMPLEADO.idEmpleado = VENTA.EMPLEADO_idEmpleado;

/* RIGHT */
SELECT *
FROM EMPLEADO
RIGHT JOIN VENTA
ON EMPLEADO.idEmpleado = VENTA.EMPLEADO_idEmpleado 
